[tools]
k3d = "latest"
kubectl = "latest"
pre-commit = "latest"
python = "3.13"
ruff = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
APP_REPO = 'devops'
GITOPS_REPO = 'devops-gitops'

[tasks.k8s-setup-local]
description = "Set up a basic Kubernetes cluster for development that builds the local images and applies them"
run = "bash ./kubernetes/setup_cluster_local"

[hooks]
enter = "bash ./scripts/setup_project"
